#:import utils kivy.utils

<DashboardScreen>:
    BoxLayout:
        orientation: "vertical"
        canvas:
            Color:
                rgba: utils.get_color_from_hex("#0d1727")
            Rectangle:
                size: self.size
                pos: self.pos
    ##----------------------Start of Top Bar-------------------#
        BoxLayout:
            orientation: "horizontal"
            size_hint:(1,0.03)
            spacing:"10"
            canvas:
                Color:
                    rgba: utils.get_color_from_hex("#121c2e")
                Rectangle:
                    size: self.size
                    pos: self.pos
            Spacer:
                size_hint:(0.75,1)
            ImageButton:
                id: minimize_btn_id
                source: "icons/minimize.png"
                size_hint: (None, None)
                height: "25dp"
                width: "35dp"
                pos_hint: {"center_y" : 0.48}
                on_release:
                    app.minimize()
            ImageButton:
                id: close_btn_id
                source: "icons/cross.png"
                size_hint: (None, None)
                height: "18dp"
                width: "18dp"
                pos_hint: {"center_y" : 0.45}
                on_release:
                    app.close()
            Spacer:
                size_hint:(0.01,1)
        ##----------------------End of Top Bar-------------------#

        Spacer:
            size_hint: (0.98,0.04)
            pos_hint:{"right": 0.99}

        BoxLayout:
            orientation: "vertical"
            size_hint:(1,0.93)

            ##----------------------Start of Top Country Search and Date Row-------------------#

            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.1)

                Label:
                    text: "Enter Country : "
                    size_hint:(0.15,0.4)
                    color: utils.get_color_from_hex("#2b2f43")
                BoxLayout:
                    orientation: "vertical"
                    size_hint: (0.25,0.4)

                    TextInput:
                        hint_text: ""
                        font_size: "15sp"
                        font_name: "barlow-reg"
                        size_hint: (1,0.83)
                        background_color: 0,0,0,0
                        foreground_color: 0.8,0.8,0.8,1
                    BoxLayout:
                        size_hint:(1,0.03)
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex("#2a2f44")
                            Rectangle:
                                size: self.size
                                pos: self.pos

                    Spacer:
                        size_hint:(1,0.03)

                ImageButton:
                    source:"icons/go.png"
                    size_hint: (0.1,0.4)
                    allow_stretch:True
                    keep_aspect: False

                Spacer:
                    size_hint:(0.55,1)

                Label:
                    id: date_id
                    text: "August 25,2020"
                    size_hint: (0.1,0.5)
                    font_size: "15sp"
                    font_name: "barlow-reg"
                    color: utils.get_color_from_hex("#2b2f43")
                Spacer:
                    size_hint:(0.02,1)

            ##----------------------End of Top Country Search and Date Row-------------------#

            Spacer:
                size_hint: (1,0.05)

            ##----------------------Start of "Confirmed Cases", "Active case", "Confirmed Death" row-------------------#

            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.425)

                ##--Start of Confirmed cases Widget ------#
                BoxLayout:
                    orientation: "vertical"
                    size_hint: (0.74,1)
                    spacing: "10"

                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex("#121c2e")
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1,0.2)
                        Spacer:
                            size_hint: (1, 0.1)
                        Label:
                            text: "Confirmed Cases"
                            size_hint:(1,0.9)
                            font_size: "35sp"
                            color: utils.get_color_from_hex("#47546e")

                    BoxLayout:
                        orientation: "vertical"
                        size_hint: (1,0.6)

                        Label:
                            id: confirmed_cases_id
                            font_size: "200sp"
                            text: "21,010"
                            font_name: "roboto-medium"
                            color: utils.get_color_from_hex("#8695ad")

                    BoxLayout:
                        orientation: "horizontal"
                        size_hint: (1,0.2)
                        Spacer:
                            size_hint:(0.45,0.6)
                        Image:
                            source: "icons/up.png"
                            size_hint:(0.05,0.4)
                            pos_hint:{"center_y":0.5}

                        Label:
                            text: "134"
                            font_size: "22sp"
                            font_name: "roboto-medium"
                            size_hint: (0.05,0.6)
                            color: utils.get_color_from_hex("#500721")
                            pos_hint: {"center_y":0.5}

                        Spacer:
                            size_hint:(0.45,0.6)

                ##--End of Confirmed cases Widget ------#

                BoxLayout:
                    orientation: "vertical"
                    size_hint: (0.26,1)
                    spacing: "10"


            ##----------------------End of "Confirmed Cases", "Active case", "Confirmed Death" row-------------------#

            BoxLayout:
                orientation: "horizontal"
                size_hint: (1,0.355)
